  @Test
  public void testBackupOnCommit() throws Exception {
    final BackupStatusChecker backupStatus
      = new BackupStatusChecker(leaderClient, "/" + DEFAULT_TEST_CORENAME + "/replication");

    final String lastBackupDir = backupStatus.checkBackupSuccess();
    // sanity check no backups yet
    assertNull("Already have a successful backup",
               lastBackupDir);
    
    //Index
    int nDocs = BackupRestoreUtils.indexDocs(leaderClient, DEFAULT_TEST_COLLECTION_NAME, docsSeed);
    
    final String newBackupDir = backupStatus.waitForDifferentBackupDir(lastBackupDir, 30);
    //Validate
    verify(Paths.get(leader.getDataDir(), newBackupDir), nDocs);
  }

