  @Test
  public void ignoresFailures() throws Exception {
    CompletableFuture<List<Integer>> results = Async.waitForAllSuccessfulResponses(Arrays.asList(
        CompletableFuture.completedFuture(1),
        failedFuture()
    ));

    List<Integer> values = results.get();

    assertEquals(Collections.singletonList(1), values);
  }

