  @Test
  public void testBackupUnexpectedFailuresResultIn500Exception() {
    final Throwable cause = new NullPointerException();
    whenUnexpectedErrorOccursDuringCoreAdminOp(cause);

    Exception ex = expectThrows(Exception.class, () ->  CoreAdminOperation.BACKUPCORE_OP.execute(callInfo));
    assertSolrExceptionWithCodeAndCause(ex, ErrorCode.SERVER_ERROR.code, cause);
  }

