  @Test
  public void testBackupUnexpectedFailuresResultIn500Exception() {
    final Throwable cause = new NullPointerException();
    whenUnexpectedErrorOccursDuringCoreAdminOp(cause);
    
    try {
      CoreAdminOperation.BACKUPCORE_OP.execute(callInfo);
      fail("Expected backup-core execution to fail with exception.");
    } catch  (Exception thrown) {
      assertSolrExceptionWithCodeAndCause(thrown, ErrorCode.SERVER_ERROR.code, cause);
    }  
  }

