  @Test
  public void testMaxErrorsDefault() throws IOException {
    try {
      // by default the TolerantUpdateProcessor accepts all errors, so this batch should succeed with 10 errors.
      assertAddsSucceedWithErrors("tolerant-chain-max-errors-not-set", docs, null, badIds);
    } catch(Exception e) {
      fail("Shouldn't get an exception for this batch: " + e.getMessage());
    }
    assertU(commit());
    assertQ(req("q","*:*")
        ,"//result[@numFound='10']");
  }

